/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanson_test_JoinSplit */

#ifndef _Included_com_hanson_test_JoinSplit
#define _Included_com_hanson_test_JoinSplit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanson_test_JoinSplit
 * Method:    prove
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JoinSplit_prove
  (JNIEnv *, jobject);

/*
 * Class:     com_hanson_test_JoinSplit
 * Method:    generateAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JoinSplit_generateAddress
  (JNIEnv *, jobject);

/*
 * Class:     com_hanson_test_JoinSplit
 * Method:    verify
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_JoinSplit_verify
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
